
# Example config file.
# Here we create two sessions.
# One with docker containers and the other with tmux man page.


docker: # session name

  redis: # window name
    cmd: docker run redis -e PWD=$REDIS_PASSWORD
    env:
      REDIS_PASSWORD: 123456

  kafka: 
    cmd: cd ~/path/to/kafka/compose && docker-compose up


tmux-man:
  manual:
    cwd: ~/
    cmd: man tmux

foo:
  bar:
    cwd: /
    cmd: ls

multi:
  line:
    cmd:
      echo "this will execute in order"

      echo "using newlines as an ENTER key"

      echo "to run a sequence of commands"

