
on: push

jobs:

  build:
    name: Build rTMUXer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
      - run: RUSTFLAGS='-C link-arg=-s' cargo build --release --target x86_64-unknown-linux-musl
      - run: cd target/x86_64-unknown-linux-musl/release && tar -czvf rtmuxer.tar.gz rtmuxer && cd ../../..
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rtmuxer
          path: target/x86_64-unknown-linux-musl/release/rtmuxer.tar.gz


  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v3
      - run: ls -la -R
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: rtmuxer/rtmuxer.tar.gz

