
on: push

jobs:

  build:
    name: Build rTMUXer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rtmuxer
          path: target/release/rtmuxer


  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v3
      - run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: rtmuxer/rtmuxer
